backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: project
    label: Projects
    folder: src/pages/projects
    create: true
    fields:
    - label: 'Template Key'
      name: templateKey
      widget: hidden
      default: project
    -
      label: Title
      name: title
      widget: string
    - {label: "Tags", name: "tags", widget: "list"}
    -
      label: Date
      name: date
      widget: datetime
    -
      label: Category
      name: category
      widget: select
      options:
      - 'Enterprise Solution'
      - Blockchain
      - 'Booking & Event Platforms'
      - E-commerce
      - Fintech
    - label: 'Small description'
      name: smallDescr
      widget: text
    - label: 'Project Preview Image'
      name: preview
      widget: image
    -
      label: Promo
      name: promo
      widget: object
      fields:
      -
        label: Description
        name: sub
        widget: text
        default: 'Some text'
      -
        label: Link
        name: link
        widget: string
        default: 'link.com'
    -
      label: 'Clients Goals'
      name: goals
      widget: object
      fields:
      -
        label: 'Section Title'
        name: title
        widget: string
        default: 'Section Title'
      -
        label: Description
        name: descr
        widget: object
        fields:
        -
          label: 'Left Column'
          name: leftCol
          widget: text
          default: 'Some text'
        -
          label: 'Right Column'
          name: rightCol
          widget: text
          default: 'Some text'
    -
      label: Slide
      name: slider
      widget: list
      fields:
      -
        label: Image
        name: img
        widget: image
        default: 'No image provided'
    -
      label: Solutions
      name: solutions
      widget: object
      fields:
      -
        label: 'Section Title'
        name: title
        widget: string
        default: 'Section Title'
      -
        label: Description
        name: descr
        widget: object
        fields:
        -
          label: 'Left Column'
          name: leftCol
          widget: text
          default: 'Some text'
        -
          label: 'Right Column'
          name: rightCol
          widget: text
          default: 'Some text'
    -
      label: Stages
      name: stages
      widget: list
      fields:
      -
        label: 'Stage Details'
        name: stageDetails
        widget: text
        default: 'Some details'
      -
        label: 'Stage Is Completed'
        name: isComplete
        widget: boolean
        default: 'true'
    -
      label: 'Used Technologies'
      name: technologies
      widget: list
      fields:
      -
        label: 'Technology Name'
        name: name
        widget: string
        default: 'Some technology'
      -
        label: 'Technology Logo'
        name: image
        widget: image
        default: 'No image provided'
    -
      label: 'Project Results'
      name: projectResults
      widget: object
      fields:
      -
        label: Description
        name: descr
        widget: text
        default: 'Some text'
      -
        label: Result
        name: results
        widget: list
        fields:
        -
          label: 'Result Title'
          name: title
          widget: string
          default: 'Some Title'
        -
          label: 'Result Description'
          name: descr
          widget: text
          default: 'Some text'
        -
          label: 'Result Icon'
          name: icon
          widget: image
          default: 'No image provided'
    -
      label: 'Project Testimonial'
      name: testimonial
      widget: object
      fields:
      -
        label: Review
        name: description
        widget: text
        default: 'Some text'
      -
        label: Person
        name: person
        widget: object
        fields:
        -
          label: Name
          name: name
          widget: string
          default: 'Some person'
        -
          label: Photo
          name: image
          widget: image
          default: 'No image provided'
        -
          label: Occupation
          name: occupation
          widget: string
          default: 'Some occupation'
  - name: "pages"
    label: "Pages"
    files:
    -
      file: src/pages/about-us.md
      name: about
      label: 'About Us Page'
      fields:
      -
        label: 'Template Key'
        name: templateKey
        widget: hidden
        default: about-page
      -
        label: Title
        name: title
        widget: string
        default: title
      -
        label: Promo
        name: promo
        widget: object
        required: false
        fields:
        -
          label: Description
          name: sub
          widget: text
        -
          label: 'Big Logo'
          name: image
          widget: image
      -
        label: 'About Us'
        name: aboutUs
        widget: object
        required: false
        fields:
        -
          label: Title
          name: title
          widget: text
        -
          label: Description
          name: descr
          widget: text
        -
          label: Image
          name: image
          widget: image
      -
        label: 'Our Team'
        name: companyandteam
        widget: object
        fields:
        -
          label: 'Team Members'
          name: members
          widget: list
          fields:
          -
            label: 'Team Member Name'
            name: name
            widget: string
          -
            label: 'Team Member Photo'
            name: image
            widget: image
          -
            label: 'Team Member Position'
            name: occupation
            widget: string
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
